controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 1.30
  min_vel_x: 0.10
  max_rotational_vel: 1.5
  min_in_place_rotational_vel: 1.0
  acc_lim_theta: 0.75
  acc_lim_x: 0.50
  acc_lim_y: 0.50
  meter_scoring: true

  holonomic_robot: false
  yaw_goal_tolerance: 0.58
  xy_goal_tolerance: 0.25
  goal_distance_bias: 0.8
  path_distance_bias: 0.2
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

